markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Jeffrey Konowitch
url: http://jeff.konowit.ch
description: Musings about Economics Technology and more...
twitter: jkonowitch
github: jkonowitch
gravatar_url: http://gravatar.com/avatar/ecb5c4afca43c18447fea03bf29200b1